<?php

namespace StoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
    public function getPersonAddress($id)
    {
        $address = $this->getEntityManager()->createQuery(
            'SELECT a FROM StoreBundle:Address a WHERE a.id = :id'
        )->setParameter('id', $id)->getResult();
        return $address;
    }
}
